# Generated by Django 6.0.5 on 2026-05-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_billingaddress_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
